-- AUTHOR_ID 대신 저자 이름을 출력하게 만드는 격
SELECT b.BOOK_ID, a.AUTHOR_NAME, DATE_FORMAT(b.PUBLISHED_DATE, "%Y-%m-%d")
FROM BOOK b
LEFT JOIN AUTHOR a
ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY b.PUBLISHED_DATE;
